version: "3.9"

services:
  postgres: # Nome simplificado
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-net

  api:
    build: .
    container_name: user_management_api
    environment:
      DB_HOST: postgres # Aponta para o serviço 'postgres'
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_SECURITY_JWT_SECRET: ${APP_SECURITY_JWT_SECRET}
      APP_SECURITY_JWT_EXPIRATION_TIME: ${APP_SECURITY_JWT_EXPIRATION_TIME}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - user-net

volumes:
  postgres_data:

networks:
  user-net:
