spring:
  application:
    name: user-management-api
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

# Configurações customizadas
app:
  security:
    jwt:
      secret: "${APP_SECURITY_JWT_SECRET}"
      expiration-ms: "${APP_SECURITY_JWT_EXPIRATION_TIME}"

admin:
  user:
    name: ${ADMIN_USER}
    password: ${ADMIN_PASSWORD}

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
